# Generated by Django 4.2.7 on 2025-12-31 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('warning', 'Предупреждение'), ('info', 'Информация'), ('moderation', 'Модерация'), ('support', 'Поддержка'), ('announcement', 'Объявление')], max_length=20)),
                ('content', models.TextField()),
                ('available_variables', models.JSONField(blank=True, default=list, help_text="Список доступных переменных: ['user_name', 'project_title', etc.]")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_message_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'db_table': 'message_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField(help_text='ID чата из приложения chat')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_system_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.messagetemplate')),
            ],
            options={
                'verbose_name': 'Системное сообщение',
                'verbose_name_plural': 'Системные сообщения',
                'db_table': 'system_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('target_audience', models.CharField(choices=[('all', 'Все пользователи'), ('active', 'Активные пользователи'), ('contractors', 'Подрядчики'), ('clients', 'Клиенты'), ('specific', 'Конкретные пользователи')], max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланировано'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push уведомление',
                'verbose_name_plural': 'Push уведомления',
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('target_audience', models.CharField(choices=[('all', 'Все пользователи'), ('active', 'Активные пользователи'), ('contractors', 'Подрядчики'), ('clients', 'Клиенты'), ('specific', 'Конкретные пользователи')], max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('bounced_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sending', 'Отправляется'), ('sent', 'Отправлена'), ('failed', 'Ошибка')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email кампания',
                'verbose_name_plural': 'Email кампании',
                'db_table': 'email_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(choices=[('728x90', 'Leaderboard (728x90)'), ('300x250', 'Medium Rectangle (300x250)'), ('320x50', 'Mobile Banner (320x50)'), ('300x600', 'Half Page (300x600)'), ('970x250', 'Billboard (970x250)')], max_length=10)),
                ('placement', models.CharField(choices=[('home', 'Главная страница'), ('projects', 'Страницы проектов'), ('profiles', 'Профили пользователей'), ('search', 'Страница поиска'), ('dashboard', 'Дашборд пользователя')], max_length=20)),
                ('priority', models.IntegerField(default=1, help_text='Чем выше число, тем выше приоритет')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активный'), ('paused', 'Приостановлен'), ('expired', 'Истек'), ('rejected', 'Отклонен')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('impressions_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ab_test_group', models.CharField(blank=True, help_text='A, B, C и т.д.', max_length=10)),
                ('ab_test_weight', models.IntegerField(default=100, help_text='Вес для A/B тестирования (0-100)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'db_table': 'banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
