# Generated by Django 4.2.7 on 2025-12-30 15:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ad Category',
                'verbose_name_plural': 'Ad Categories',
                'db_table': 'ad_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='advertisements/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner'), ('slider', 'Slider'), ('popup', 'Popup'), ('sponsored', 'Sponsored Content')], default='banner', max_length=20)),
                ('position', models.CharField(choices=[('home_slider', 'Home Page Slider'), ('home_banner', 'Home Page Banner'), ('search_results', 'Search Results'), ('project_details', 'Project Details'), ('profile_page', 'Profile Page')], default='home_slider', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('contractors', 'Contractors Only'), ('clients', 'Clients Only')], default='all', max_length=20)),
                ('background_color', models.CharField(default='#f97316', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher number = higher priority', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'db_table': 'advertisements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='advertisements.advertisement')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_assignments', to='advertisements.adcategory')),
            ],
            options={
                'db_table': 'ad_category_assignments',
                'unique_together': {('advertisement', 'category')},
            },
        ),
    ]
