# Generated by Django 4.2.7 on 2025-12-30 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_project_updates', models.BooleanField(default=True)),
                ('email_new_messages', models.BooleanField(default=True)),
                ('email_applications', models.BooleanField(default=True)),
                ('email_reviews', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('push_project_updates', models.BooleanField(default=True)),
                ('push_new_messages', models.BooleanField(default=True)),
                ('push_applications', models.BooleanField(default=True)),
                ('push_reviews', models.BooleanField(default=True)),
                ('inapp_project_updates', models.BooleanField(default=True)),
                ('inapp_new_messages', models.BooleanField(default=True)),
                ('inapp_applications', models.BooleanField(default=True)),
                ('inapp_reviews', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('project_application', 'Project Application'), ('application_accepted', 'Application Accepted'), ('application_rejected', 'Application Rejected'), ('project_completed', 'Project Completed'), ('project_update', 'Project Update'), ('new_message', 'New Message'), ('review_received', 'Review Received'), ('payment_reminder', 'Payment Reminder'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx')],
            },
        ),
    ]
